/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package valeryfonseca.proyecto1;
// import java.util.Date; --- IGNORE ---

import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author Valery
 */
import java.awt.Color;

public class UpsertCelebracion extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpsertCelebracion.class.getName());

    /**
     * Creates new form UpsertCelebracion
     */
    ControlCelebraciones control;
    private int idCelebracion;
    private char accionRealizar = 'a'; // a = agregar, e = editar

    public UpsertCelebracion(ControlCelebraciones control, Celebracion celebracion) {
        this.control = control;
        initComponents();
        jPanelMensaje.setVisible(false);
        if (celebracion != null) {
            this.idCelebracion = celebracion.getId();
            this.accionRealizar = 'e';
            id.setText(String.valueOf(this.idCelebracion));
            pais.setText(celebracion.getPais());
            fecha.setDate(celebracion.getFecha());
            jareaDescripcion.setText(celebracion.getDescripcion());
            jLabelTitle.setText("Editar celebración");
            this.setTitle("Editar Celebración");

        } else {
            jLabelTitle.setText("Agregar celebración");
            this.setTitle("Agregar Celebración");
            this.idCelebracion = control.reserveId();
        }
        id.setText(String.valueOf(this.idCelebracion));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        pais = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jareaDescripcion = new javax.swing.JTextArea();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabelTitle = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jBtnCerrar = new javax.swing.JButton();
        jPanelMensaje = new javax.swing.JPanel();
        jBtnCerrarMensaje = new javax.swing.JButton();
        jMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID:");

        jLabel2.setText("País:");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Descripción:");

        id.setEditable(false);
        id.setEnabled(false);
        id.setFocusable(false);

        jareaDescripcion.setColumns(20);
        jareaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jareaDescripcion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pais)
                            .addComponent(id))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        id.getAccessibleContext().setAccessibleName("id");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 81, 625, -1));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setText("Agregar celebración");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 183, -1));

        btnGuardar.setBackground(new java.awt.Color(0, 204, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 160, 40));

        jBtnCerrar.setBackground(new java.awt.Color(255, 51, 51));
        jBtnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 160, 40));

        jPanelMensaje.setBackground(new java.awt.Color(255, 255, 255));

        jBtnCerrarMensaje.setBackground(new java.awt.Color(255, 102, 102));
        jBtnCerrarMensaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnCerrarMensaje.setText("X");
        jBtnCerrarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCerrarMensajeActionPerformed(evt);
            }
        });

        jMensaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMensaje.setToolTipText("");

        javax.swing.GroupLayout jPanelMensajeLayout = new javax.swing.GroupLayout(jPanelMensaje);
        jPanelMensaje.setLayout(jPanelMensajeLayout);
        jPanelMensajeLayout.setHorizontalGroup(
            jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMensajeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCerrarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanelMensajeLayout.setVerticalGroup(
            jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMensajeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCerrarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 480, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {

            int idVal = Integer.parseInt(id.getText());
            Date nuevaFecha = fecha.getDate();
            String descripcion = jareaDescripcion.getText();
            String paisVal = pais.getText();
            Celebracion nueva = new Celebracion(idVal, nuevaFecha, descripcion, paisVal);
            String validacion = control.validarCelebracion(nueva);
            if (validacion != null) {
                jMensaje.setText(validacion);
                jMensaje.setForeground(Color.RED);
                jPanelMensaje.setVisible(true);
            } else {
                if (this.accionRealizar == 'e') {
                    control.actualizarCelebracion(nueva);
                    jMensaje.setText("Celebración editada exitosamente");
                } else {
                    control.addCelebracion(nueva);
                    jMensaje.setText("Celebración agregada exitosamente");
                    this.idCelebracion = control.reserveId();
                    id.setText(String.valueOf(this.idCelebracion));
                    pais.setText("");
                    fecha.setDate(null);
                    jareaDescripcion.setText("");
                }
                jPanelMensaje.setVisible(true);
                jMensaje.setForeground(Color.GREEN);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jBtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarActionPerformed

    private void jBtnCerrarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCerrarMensajeActionPerformed
        // TODO add your handling code here:
        jMensaje.setText("");
        jPanelMensaje.setVisible(false);
    }//GEN-LAST:event_jBtnCerrarMensajeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JTextField id;
    private javax.swing.JButton jBtnCerrar;
    public javax.swing.JButton jBtnCerrarMensaje;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTitle;
    public javax.swing.JLabel jMensaje;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMensaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jareaDescripcion;
    private javax.swing.JTextField pais;
    // End of variables declaration//GEN-END:variables
}
