/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package valeryfonseca.proyecto1;

/**
 *
 * @author Valery
 */
import valeryfonseca.proyecto1.UpsertCelebracion;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Iterator;

public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    private ControlCelebraciones control = new ControlCelebraciones();

    public VentanaPrincipal() {
        initComponents();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCelebraciones = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnNuevaCelebracion = new javax.swing.JButton();
        jbtnBuscar = new javax.swing.JButton();
        jbtnInvertirPaises = new javax.swing.JButton();
        jbtnOrdenar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMensajeError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCelebraciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID de la celebración", "País", "Fecha", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCelebraciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 690, 280));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo.setText("Celebraciones");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(392, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(366, 366, 366))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevaCelebracion.setBackground(new java.awt.Color(91, 204, 111));
        btnNuevaCelebracion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevaCelebracion.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaCelebracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valeryfonseca/proyecto1/add.png"))); // NOI18N
        btnNuevaCelebracion.setText("Nueva celebración");
        btnNuevaCelebracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCelebracionActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevaCelebracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 204, 52));
        btnNuevaCelebracion.getAccessibleContext().setAccessibleName("nuevaCelebración");
        btnNuevaCelebracion.getAccessibleContext().setAccessibleDescription("");

        jbtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valeryfonseca/proyecto1/search.png"))); // NOI18N
        jbtnBuscar.setText("Buscar y Editar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 204, 45));

        jbtnInvertirPaises.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valeryfonseca/proyecto1/list.png"))); // NOI18N
        jbtnInvertirPaises.setText("Lista Paises Invertidos");
        jbtnInvertirPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInvertirPaisesActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnInvertirPaises, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 204, 52));

        jbtnOrdenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valeryfonseca/proyecto1/sort.png"))); // NOI18N
        jbtnOrdenar.setText("Ordenar Celebraciones");
        jbtnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 204, 49));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 220, 260));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Acciones");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 220, 40));

        jLabelMensajeError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMensajeError.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabelMensajeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 490, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaCelebracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCelebracionActionPerformed
        // TODO add your handling code here:
        UpsertCelebracion ventana = new UpsertCelebracion(this.control, null);
        jLabelMensajeError.setText("");
        ventana.setVisible(true);
        ventana.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                actualizarTabla();
            }
        });
    }//GEN-LAST:event_btnNuevaCelebracionActionPerformed

    private void jbtnInvertirPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInvertirPaisesActionPerformed
        // TODO add your handling code here:
        int cantidadCelebraciones = control.cantidadCelebraciones();
        if (cantidadCelebraciones == 0) {
            jLabelMensajeError.setText("No hay Paises para invertir.");
            jLabelMensajeError.setVisible(true);
        } else {

            PaisesInvertidosForm paisesInvertidosForm = new PaisesInvertidosForm(control);
            paisesInvertidosForm.setVisible(true);
        }
    }//GEN-LAST:event_jbtnInvertirPaisesActionPerformed

    private void jbtnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOrdenarActionPerformed
        // TODO add your handling code here:
        int cantidadCelebraciones = control.cantidadCelebraciones();
        if (cantidadCelebraciones == 0) {
            jLabelMensajeError.setText("No hay celebraciones para ordenar.");
            jLabelMensajeError.setVisible(true);
        } else {

            OrdenarCelebracion ordenarForm = new OrdenarCelebracion(control);
            ordenarForm.setVisible(true);
        }
    }//GEN-LAST:event_jbtnOrdenarActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        // TODO add your handling code here:
        int cantidadCelebraciones = control.cantidadCelebraciones();
        if (cantidadCelebraciones == 0) {
            jLabelMensajeError.setText("No hay celebraciones para buscar.");
            jLabelMensajeError.setVisible(true);
        } else {
            VentanaBusqueda ventanaBusqueda = new VentanaBusqueda(control);
            ventanaBusqueda.setVisible(true);
            ventanaBusqueda.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                    actualizarTabla();
                }
            });
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void actualizarTabla() {
        String[] columnas = {"ID de la celebración", "Fecha", "Descripción", "País"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Iterator<Celebracion> it = control.getLista().iterator();
        while (it.hasNext()) {
            Celebracion c = it.next();
            Object[] fila = new Object[]{
                c.getIdCelebracion(),
                c.getFecha() == null ? "" : sdf.format(c.getFecha()),
                c.getDescripcion(),
                c.getPais()
            };
            modelo.addRow(fila);
        }
        tablaCelebraciones.setModel(modelo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevaCelebracion;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelMensajeError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnInvertirPaises;
    private javax.swing.JButton jbtnOrdenar;
    private javax.swing.JTable tablaCelebraciones;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
